### ISSUE TITLE
Example of adisk.jpg?

### ISSUE THREAD

**Issue by mkarbach** [rantonels/starless#1]
Can you provide an example image of adisk.jpg? Doesn't have to be large, just so I get an idea of how it is supposed to show the disk. I'm guessing like it should look like a filled circle, but the rendered image doesn't look anything like my input.

**Comment by rantonels** [comment]
adisk.jpg should be: any size; x coordinate is angle, y coordinate is radius, with top corresponding to the inner radius and bottom the outer. This means the image must be seamless horizontally.

The brightness will also be used to compute alpha information, so having it taper to black at the bottom is important.

**Comment by rantonels** [comment]
An example is now provided in the README, so I guess this _can_ be closed, but I'll consider it completely over when I'll manage to switch to a completely textureless setup.

**Comment by mkarbach** [comment]
Thanks!
